### ISSUE TITLE
'rule-non-nested-empty-line-before' has been deprecated and in 8.0 will be removed

### ISSUE THREAD

**Issue by alienlebarge** [alienlebarge/stylelint-config#19]
> Deprecation Warning: 'rule-non-nested-empty-line-before' has been deprecated and in 8.0 will be removed. Instead use 'rule-empty-line-before'. See: https://stylelint.io/user-guide/rules/rule-non-nested-empty-line-before/

**Comment by octoxan** [comment]
Why was this deprecated?

rule-empty-line-before doesn't have the same functionality?

How do I tell stylelint that I want an empty line before non-nested rules, and no line before nested rules?

**Comment by rodoabad** [comment]
What's the alternative for this rule?
